config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions, except: :index
  devise_for :users
  root to: 'subscriptions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    attr_reader :duration
    validates_presence_of  :name, :price, :start_at, :category, :frequency
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :destroy, :update]
  def index
    @subscriptions = Subscription.all
    monthly = @subscriptions.select { |subscription| subscription.frequency == 'Month' }.map(&:price).sum
    two_months = @subscriptions.select { |subscription| subscription.frequency == '2 Months' }.map(&:price).sum / 2
    six_months = @subscriptions.select { |subscription| subscription.frequency == '6 Months' }.map(&:price).sum / 6
    twelve_months = @subscriptions.select { |subscription| subscription.frequency == 'Year' }.map(&:price).sum / 12
    @total = monthly + two_months + six_months + twelve_months
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.ends_at = @subscription.start_at + params['subscription']['duration'].to_i.month if params['subscription']['duration'] != 'Unlimited'
    if @subscription.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @subscription.update(subscription_params)
      redirect_to subscription_path(@subscription)
    else
      render :edit
    end
  end

  def destroy
    @subscription.destroy
    redirect_to root_path
  end

  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:name, :price, :start_at, :ends_at, :category, :frequency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json.erb' %>">
    <%= render 'shared/ios_pwa_links' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row align-items-center" style="min-height: calc(100vh - 70px);">
        <div class="col-xs-12 col-md-6 offset-md-3">
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-6 offset-md-3 p-0">
          <%= render 'shared/navbar' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mt-2 d-flex justify-content-around">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "icons/android-icon-192x192.png" %>
    <% end %>
</div>

app/views/subscriptions/_form.html.erb
<%= simple_form_for(subscription) do |f| %>
    <%= f.input :name %>
    <%= f.input :price, label: 'Price (£ - pounds)' %>
    <%= f.input :category, collection: ['Food', 'Insurance', 'Bills', 'Sport', 'Rusty', 'Leisure' ].sort + ['Other'] %>
    <%= f.input :start_at, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :duration, collection: ['Unlimited'] + (1..36).to_a, label: 'Duration (months)' %>
    <%= f.input :frequency, collection: ['Month', '2 Months', '6 Months', 'Year'], label: 'Payment every...' %>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/destroy.html.erb
<h1>Subscriptions#destroy</h1>
<p>Find me in app/views/subscriptions/destroy.html.erb</p>

app/views/subscriptions/edit.html.erb
<%= render 'form', subscription: @subscription %>

app/views/subscriptions/index.html.erb
<% @subscriptions.each do |subscription| %>
    <%= link_to subscription_path(subscription), class: "text-dark text-decoration-none" do %>
        <div class="card mt-2">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <h3 class="m-0"><%= subscription.name %></h3>
                    <p class="m-0"><strong>£<%= subscription.price %></strong></p>
                </div>
            </div>
        </div>
    <% end %>    
<% end %>
<div class="d-flex justify-content-between align-items-center mt-3 p-2">
    <h3 class="m-0">Total:</h3>
    <p class="m-0"><strong>£<%= number_with_precision(@total, precision: 2) %></strong></p>
</div>
<div class="d-flex justify-content-around align-items-center mt-3 p-2">
    <%= link_to "New", new_subscription_path, class: "btn btn-primary" %>
</div>

app/views/subscriptions/new.html.erb
<%= render 'form', subscription: @subscription %>

app/views/subscriptions/show.html.erb
<div class="card">
    <div class="card-header">
        <strong><%= @subscription.name.capitalize %></strong>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between p-2 align-items-center">
            <div>
                <h6 class="card-title font-weight-light">Start Date</h6>
                <h6 class="card-subtitle mb-2 text-muted font-weight-bold"><%= @subscription.start_at %></h6>
                <h6 class="card-title font-weight-light">End Date</h6>
                <h6 class="card-subtitle mb-2 text-muted font-weight-bold"><%= @subscription.ends_at.nil? ? 'Unlimited' : @subscription.ends_at %></h6>
                <h6 class="card-title font-weight-light">Price</h6>
                <h6 class="card-subtitle mb-2 text-muted font-weight-bold">£<%= number_with_precision(@subscription.price, precision: 2) %></h6>
            </div>
            <div>
                <h6 class="card-title font-weight-light">Category</h6>
                <h6 class="card-subtitle mb-2 text-muted font-weight-bold"><%= @subscription.category %></h6>
                <h6 class="card-title font-weight-light">Frequency</h6>
                <h6 class="card-subtitle mb-2 text-muted font-weight-bold"><%= @subscription.frequency %></h6>
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <%= link_to 'Edit', edit_subscription_path(@subscription), class: "btn btn-primary" %>
            <%= link_to 'Delete', subscription_path(@subscription), method: :delete, class: "btn btn-danger" %>
        </div>
    </div>
</div>

app/views/subscriptions/update.html.erb
<h1>Subscriptions#update</h1>
<p>Find me in app/views/subscriptions/update.html.erb</p>